/** The contract's validation surface. Each boundary lives in its own module; this is the door. */

// Re-exports only. New validation belongs in the boundary module it guards, not
// here — a façade that people append to grows back into the file it replaced.
// Note also that `validate/` must never gain an `index.ts`: the `@shared/…` and
// `#shared/…` aliases resolve file-before-directory, so this module wins today,
// and a directory index would make which one wins a resolver detail.

/* —— Boundary modules —— */

export {
  arrayOf,
  booleanValue,
  boundedClaimText,
  BROWSER_SCALAR_MESSAGES,
  claimEstimateMinutes,
  contractSetMember,
  ContractValidationError,
  exact,
  identifier,
  integer,
  type JsonRecord,
  NAMED_EXACT_MESSAGES,
  PATH_EXACT_MESSAGES,
  positiveClaimInteger,
  prose,
  record,
  stringValue,
  timestamp,
} from "./validate/scalars.js";
export {
  parseAgentEntity,
  parseAgentTaskPhaseResponse,
  parseBoardNotification,
  parseBoardPause,
  parseDesignRecordDraft,
  parseDesignRecordEntity,
  type ParsedWorkItemTransition,
  parseEventEntity,
  parseFindingsLedger,
  parseGateAction,
  parseHandoffEntity,
  parseInterruptEntity,
  parseMessageEntity,
  parseNodeEntity,
  parseParkRecord,
  parseParksLedger,
  parsePipelineSummaryEntity,
  parsePlanEntity,
  parseProjectArtifactEntity,
  parseProjectEntity,
  parseProjectEventEntity,
  parseQuestionEntity,
  parseReviewFindingDraft,
  parseReviewFindingEntity,
  parseRunEntity,
  parseTaskEntity,
  parseTaskPhaseEntity,
  parseWorkItemAudit,
  parseWorkItemEntity,
  parseWorkItemTransitionEntity,
  projectAgentTaskPhase,
  type TolerantBoardNotification,
  type TolerantDeclaredChild,
  type TolerantDesignRecordEntity,
  type TolerantFindingsLedger,
  type TolerantGateAction,
  type TolerantParkRecord,
  type TolerantParksLedger,
  type TolerantPlanRevision,
  type TolerantReviewFindingEntity,
  type TolerantTaskEntity,
  type TolerantWorkItemAudit,
  type TolerantWorkItemEntity,
} from "./validate/entities.js";
export {
  automationConfigurationPartsBytes,
  parseAutomationAgentTypeEntity,
  parseAutomationConfigurationEntity,
  parseAutomationExecutorEntity,
  parseAutomationStageEntity,
  parseBoardSnapshotEntity,
  parseClaimRunPausedResult,
  parseClaimRunResult,
  skillIdentifier,
  validateAutomationConfigurationParts,
} from "./validate/board.js";
export {
  parseWorkerAgentContext,
  parseWorkerAgentRunOutput,
  parseWorkerTaskWakeClaim,
  publishedInterfaceValidationReason,
  type StageHandoffDraft,
  WorkerAgentContextBudgetError,
  workerAgentContextUsage,
  type WorkerAgentContextUsage,
  type WorkflowPlanDraft,
} from "./validate/worker.js";
export { parseWorkerAgentRunOutcome, parseWorkflowPlanDraft, validateWorkflowPlanChildren } from "./validate/plans.js";
export {
  parseBoardAgentMessage,
  parseBoardAnswer,
  parseBoardApprovePipelineMerge,
  parseBoardAttestDeploy,
  parseBoardAutomationUpdate,
  parseBoardBacklogTask,
  parseBoardClaim,
  parseBoardConfirmPlan,
  parseBoardCreateAgent,
  parseBoardCreateProject,
  parseBoardCreateTask,
  parseBoardCreateTaskPhase,
  parseBoardCreateWorkItem,
  parseBoardHumanMessage,
  parseBoardIdempotencyKey,
  parseBoardIdentifier,
  parseBoardInterrupt,
  parseBoardLaneErrorDetail,
  parseBoardQuestion,
  parseBoardRejectFinalApproval,
  parseBoardRejectPlan,
  parseBoardResume,
  parseBoardRetryTask,
  parseBoardRotateAgentToken,
  parseBoardSettle,
  parseBoardUpdateProject,
  parseBoardUpdateTask,
  parseBoardUpdateTaskPhase,
  parseBoardUpdateWorkItem,
} from "./validate/requests.js";
